### ISSUE TITLE
Request to build 32bit version of the VirtualXposed

### ISSUE THREAD

**Issue by Ananas-Kuchen** [so-lli/VirtualXposed_12#2]
**Is your feature request related to a problem? Please describe.**

Due to the actual developer discontinuing the armeabi-v7a version, the apk bundle installation feature introduced in the arm64-v8a version cannot be found in the old armeabi-v7a version

**Describe the solution you'd like**

I would like to ask you to build another version of this app with armeabi-v7a architecture support

**Describe alternatives you've considered**

Because the package name is 64, please make a version of armeabi-v7a with package name is 32

**Additional context**

If you can build another 32bit version of this app with bundle app install support it will help me a lot

**Comment by imsourcandy** [comment]
Almost all modern phones use 64-bit processors. For older versions use version 0.18.2

**Comment by Ananas-Kuchen** [comment]
> Almost all modern phones use 64-bit processors. For older versions use version 0.18.2

Of course new phones must use 64bit apps. but no 64bit phones leave 32bit support, if so then the old games left with only 32bit / x86 ABI can't be played on new phones for nostalgia. although it's rare but it's possible that there are still phone users who do that

I just need split/bundle app installer support apart from xposed and gg functions, the problem is version 0.18.2 doesn't support apks/xapk and playstore converts all apps to bundles instead apk

If I had more finances and could buy a computer and could understand programming, I wouldn't have to beg for this from anyone in the first place

At least please make a 32bit version with installation support even once, of course don't leave Xposed and Gameguardian support because I still need them
