### ISSUE TITLE
Android 11 All Files Permission

### ISSUE THREAD

**Issue by ghost** [so-lli/VirtualXposed_12#3]
![Screenshot_20220203-155428_Settings](https://user-images.githubusercontent.com/82843871/152346898-c968f5f9-59b8-414c-990d-e1f589736fd2.png)

Please Add android.permission.MANAGE_EXTERNAL_STORAGE

**Comment by imsourcandy** [comment]
Thanks for your feedback. 
I added this permission in latest release, you can download it at https://github.com/so-lli/VirtualXposed_12/releases/tag/0.21.2
